# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_models_api import (
    CustomSpeechModelsApi,
)  # noqa: E501


class TestCustomSpeechModelsApi(unittest.TestCase):
    """CustomSpeechModelsApi unit test stubs"""

    def setUp(self):
        self.api = (
            swagger_client.api.custom_speech_models_api.CustomSpeechModelsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_model_to_subscription(self):
        """Test case for copy_model_to_subscription

        Copies a model from one subscription to another.  # noqa: E501
        """

    def test_create_model(self):
        """Test case for create_model

        Creates a new model.  # noqa: E501
        """

    def test_delete_model(self):
        """Test case for delete_model

        Deletes the model identified by the given ID.  # noqa: E501
        """

    def test_get_base_model(self):
        """Test case for get_base_model

        Gets the base model identified by the given ID.  # noqa: E501
        """

    def test_get_base_model_manifest(self):
        """Test case for get_base_model_manifest

        Returns an manifest for this base model which can be used in an on-premise container.  # noqa: E501
        """

    def test_get_base_models(self):
        """Test case for get_base_models

        Gets the list of base models for the authenticated subscription.  # noqa: E501
        """

    def test_get_model(self):
        """Test case for get_model

        Gets the model identified by the given ID.  # noqa: E501
        """

    def test_get_model_manifest(self):
        """Test case for get_model_manifest

        Returns an manifest for this model which can be used in an on-premise container.  # noqa: E501
        """

    def test_get_models(self):
        """Test case for get_models

        Gets the list of custom models for the authenticated subscription.  # noqa: E501
        """

    def test_get_supported_locales_for_models(self):
        """Test case for get_supported_locales_for_models

        Gets a list of supported locales for model adaptation.  # noqa: E501
        """

    def test_update_model(self):
        """Test case for update_model

        Updates the metadata of the model identified by the given ID.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
