# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_projects_api import (
    CustomSpeechProjectsApi,
)  # noqa: E501


class TestCustomSpeechProjectsApi(unittest.TestCase):
    """CustomSpeechProjectsApi unit test stubs"""

    def setUp(self):
        self.api = (
            swagger_client.api.custom_speech_projects_api.CustomSpeechProjectsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Creates a new project.  # noqa: E501
        """

    def test_delete_project(self):
        """Test case for delete_project

        Deletes the project identified by the given ID.  # noqa: E501
        """

    def test_get_datasets_for_project(self):
        """Test case for get_datasets_for_project

        Gets the list of datasets for specified project.  # noqa: E501
        """

    def test_get_endpoints_for_project(self):
        """Test case for get_endpoints_for_project

        Gets the list of endpoints for specified project.  # noqa: E501
        """

    def test_get_evaluations_for_project(self):
        """Test case for get_evaluations_for_project

        Gets the list of evaluations for specified project.  # noqa: E501
        """

    def test_get_models_for_project(self):
        """Test case for get_models_for_project

        Gets the list of models for specified project.  # noqa: E501
        """

    def test_get_project(self):
        """Test case for get_project

        Gets the project identified by the given ID.  # noqa: E501
        """

    def test_get_projects(self):
        """Test case for get_projects

        Gets the list of projects for the authenticated subscription.  # noqa: E501
        """

    def test_get_supported_project_locales(self):
        """Test case for get_supported_project_locales

        Gets the list of supported locales.  # noqa: E501
        """

    def test_get_transcriptions_for_project(self):
        """Test case for get_transcriptions_for_project

        Gets the list of transcriptions for specified project.  # noqa: E501
        """

    def test_update_project(self):
        """Test case for update_project

        Updates the project identified by the given ID.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
