# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_model_evaluations_api import (
    CustomSpeechModelEvaluationsApi,
)  # noqa: E501


class TestCustomSpeechModelEvaluationsApi(unittest.TestCase):
    """CustomSpeechModelEvaluationsApi unit test stubs"""

    def setUp(self):
        self.api = (
            swagger_client.api.custom_speech_model_evaluations_api.CustomSpeechModelEvaluationsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_create_evaluation(self):
        """Test case for create_evaluation

        Creates a new evaluation.  # noqa: E501
        """

    def test_delete_evaluation(self):
        """Test case for delete_evaluation

        Deletes the evaluation identified by the given ID.  # noqa: E501
        """

    def test_get_evaluation(self):
        """Test case for get_evaluation

        Gets the evaluation identified by the given ID.  # noqa: E501
        """

    def test_get_evaluation_file(self):
        """Test case for get_evaluation_file

        Gets one specific file (identified with fileId) from an evaluation (identified with id).  # noqa: E501
        """

    def test_get_evaluation_files(self):
        """Test case for get_evaluation_files

        Gets the files of the evaluation identified by the given ID.  # noqa: E501
        """

    def test_get_evaluations(self):
        """Test case for get_evaluations

        Gets the list of evaluations for the authenticated subscription.  # noqa: E501
        """

    def test_get_supported_locales_for_evaluations(self):
        """Test case for get_supported_locales_for_evaluations

        Gets a list of supported locales for evaluations.  # noqa: E501
        """

    def test_update_evaluation(self):
        """Test case for update_evaluation

        Updates the mutable details of the evaluation identified by its id.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
