# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.file_properties import FileProperties  # noqa: E501


class TestFileProperties(unittest.TestCase):
    """FileProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileProperties(self):
        """Test FileProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_properties.FileProperties()  # noqa: E501


if __name__ == "__main__":
    unittest.main()
