# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_endpoints_api import (
    CustomSpeechEndpointsApi,
)  # noqa: E501


class TestCustomSpeechEndpointsApi(unittest.TestCase):
    """CustomSpeechEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = (
            swagger_client.api.custom_speech_endpoints_api.CustomSpeechEndpointsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_create_endpoint(self):
        """Test case for create_endpoint

        Creates a new endpoint.  # noqa: E501
        """

    def test_delete_base_model_log(self):
        """Test case for delete_base_model_log

        Deletes one audio or transcription log that have been stored when using the default base model of a given language.  # noqa: E501
        """

    def test_delete_base_model_logs(self):
        """Test case for delete_base_model_logs

        Deletes the specified audio and transcription logs that have been stored when using the default base model of a given language. It deletes all logs before (and including) a specific day.  # noqa: E501
        """

    def test_delete_endpoint(self):
        """Test case for delete_endpoint

        Deletes the endpoint identified by the given ID.  # noqa: E501
        """

    def test_delete_endpoint_log(self):
        """Test case for delete_endpoint_log

        Deletes one audio or transcription log that have been stored for a given endpoint.  # noqa: E501
        """

    def test_delete_endpoint_logs(self):
        """Test case for delete_endpoint_logs

        Deletes the specified audio and transcription logs that have been stored for a given endpoint. It deletes all logs before (and including) a specific day.  # noqa: E501
        """

    def test_get_base_model_log(self):
        """Test case for get_base_model_log

        Gets a specific audio or transcription log for the default base model in a given language.  # noqa: E501
        """

    def test_get_base_model_logs(self):
        """Test case for get_base_model_logs

        Gets the list of audio and transcription logs that have been stored when using the default base model of a given language.  # noqa: E501
        """

    def test_get_endpoint(self):
        """Test case for get_endpoint

        Gets the endpoint identified by the given ID.  # noqa: E501
        """

    def test_get_endpoint_log(self):
        """Test case for get_endpoint_log

        Gets a specific audio or transcription log for a given endpoint.  # noqa: E501
        """

    def test_get_endpoint_logs(self):
        """Test case for get_endpoint_logs

        Gets the list of audio and transcription logs that have been stored for a given endpoint.  # noqa: E501
        """

    def test_get_endpoints(self):
        """Test case for get_endpoints

        Gets the list of endpoints for the authenticated subscription.  # noqa: E501
        """

    def test_get_supported_locales_for_endpoints(self):
        """Test case for get_supported_locales_for_endpoints

        Gets a list of supported locales for endpoint creations.  # noqa: E501
        """

    def test_update_endpoint(self):
        """Test case for update_endpoint

        Updates the metadata of the endpoint identified by the given ID.  # noqa: E501
        """


if __name__ == "__main__":
    unittest.main()
