# coding: utf-8

"""
    Speech Services API v3.0

    Speech Services API v3.0.  # noqa: E501

    OpenAPI spec version: v3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.model_manifest import ModelManifest  # noqa: E501


class TestModelManifest(unittest.TestCase):
    """ModelManifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelManifest(self):
        """Test ModelManifest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_manifest.ModelManifest()  # noqa: E501


if __name__ == "__main__":
    unittest.main()
